<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="eduscan_logo.png" />
    <None Remove="eduscan_logo_pos_58.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="eduscan_logo.png" />
    <EmbeddedResource Include="eduscan_logo_pos_58.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

</Project>
